# Conda environment for the arQus Twinning 2022 Norway
# Install:    conda env create -f environment.yml
# Activate:   conda activate arqus_school_2022
# Deactivate: conda deactivate

name: arqus_school_2022

dependencies:
  - python==3.9
  - numpy>=1.2
  - scipy>=1
  - astropy>=5
  - matplotlib
  - gammapy==0.20
